spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: qwerty
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml