spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: qwerty
    driver-class-name: com.mysql.cj.jdbc.Driver


